//
//  MidStudySurveySchedule.swift
//  OpenResearchKit
//
//  Created by Lennart Fischer on 26.08.26.
//

import Foundation

/// The rule that places a mid-study survey window on a timeline. Its optional
/// expiry duration is always measured from survey availability.
public enum MidStudySurveySchedule: Equatable, Sendable {

    /// A window that becomes available after an offset from participant consent.
    case relativeToConsent(
        availableAfter: TimeInterval,
        expiresAfter: TimeInterval?
    )

    /// A window that becomes available at a fixed calendar date.
    case fixedDates(
        availableAt: Date,
        expiresAfter: TimeInterval?
    )

    func validated() -> Self {
        switch self {
        case let .relativeToConsent(availableAfter, expiresAfter):
            precondition(
                availableAfter.isFinite,
                "availableAfter must be finite."
            )

            if let expiresAfter {
                precondition(
                    expiresAfter.isFinite && expiresAfter > 0,
                    "expiresAfter must be finite and greater than zero."
                )
            }

        case let .fixedDates(availableAt, expiresAfter):
            precondition(
                availableAt.timeIntervalSinceReferenceDate.isFinite,
                "availableAt must be finite."
            )

            if let expiresAfter {
                precondition(
                    expiresAfter.isFinite && expiresAfter > 0,
                    "expiresAfter must be finite and greater than zero."
                )
            }
        }

        return self
    }

    func resolved(relativeTo consentDate: Date) -> MidStudySurveyWindow {
        let availableAt: Date
        let expiresAfter: TimeInterval?

        switch self {
        case let .relativeToConsent(availableAfter, configuredExpiresAfter):
            availableAt = consentDate.addingTimeInterval(availableAfter)
            expiresAfter = configuredExpiresAfter

        case let .fixedDates(configuredAvailableAt, configuredExpiresAfter):
            availableAt = configuredAvailableAt
            expiresAfter = configuredExpiresAfter
        }

        return MidStudySurveyWindow(
            availableAt: availableAt,
            expiresAt: expiresAfter.map(availableAt.addingTimeInterval)
        )
    }

    func compareAvailability(
        to other: MidStudySurveySchedule
    ) -> ComparisonResult? {
        let lhs: TimeInterval
        let rhs: TimeInterval

        switch (self, other) {
        case let (
            .relativeToConsent(availableAfter: lhsValue, expiresAfter: _),
            .relativeToConsent(availableAfter: rhsValue, expiresAfter: _)
        ):
            lhs = lhsValue
            rhs = rhsValue

        case let (
            .fixedDates(availableAt: lhsValue, expiresAfter: _),
            .fixedDates(availableAt: rhsValue, expiresAfter: _)
        ):
            lhs = lhsValue.timeIntervalSinceReferenceDate
            rhs = rhsValue.timeIntervalSinceReferenceDate

        default:
            return nil
        }

        if lhs == rhs {
            return .orderedSame
        }

        return lhs < rhs ? .orderedAscending : .orderedDescending
    }

    var defaultIdentifierComponent: String {
        switch self {
        case let .relativeToConsent(availableAfter, _):
            // Preserve identifiers generated by the original relative API.
            return "\(availableAfter.bitPattern)"

        case let .fixedDates(availableAt, _):
            // Preserve identifiers generated by the original fixed-date API.
            return "\(availableAt.timeIntervalSinceReferenceDate.bitPattern)"
        }
    }

}
